spring.task.scheduling.pool.size=10
spring.task.execution.pool.core-size=20
spring.task.execution.pool.max-size=100
spring.task.execution.pool.queue-capacity=200


seckill.cron=0 0 3 * * ?


spring.session.store-type=redis

spring.thymeleaf.cache=false

management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true

#spring.zipkin.base-url=http://your-zipkin-host:9411/
#spring.zipkin.discovery-client-enabled=false
#spring.zipkin.sender.type=web
#spring.sleuth.sampler.probability=1
