spring.cache.type=redis

spring.cache.redis.time-to-live=3600000
spring.cache.redis.cache-null-values=true
spring.cache.redis.use-key-prefix=true

joymall.threadpool.core-size=20
joymall.threadpool.max-size=200
joymall.threadpool.keep-alive-time=10


spring.thymeleaf.cache: false 
spring.thymeleaf.mode: LEGACYHTML5

management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true

#spring.zipkin.base-url=http://your-zipkin-host:9411/
#spring.zipkin.discovery-client-enabled=false
#spring.zipkin.sender.type=web
#spring.sleuth.sampler.probability=1
