management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true


#spring.zipkin.base-url=http://your-zipkin-host:9411/
#spring.zipkin.discovery-client-enabled=false
#spring.zipkin.sender.type=web
#spring.sleuth.sampler.probability=1
