server.tomcat.max-connections=20000

logging.level.com.alibaba.nacos.client.*:warn


spring.cloud.sentinel.transport.port=8719
spring.cloud.sentinel.transport.dashboard=your-sentinel-dashboard:8858
management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true


#spring.zipkin.base-url=http://your-zipkin-host:9411/
#spring.zipkin.discovery-client-enabled=false
#spring.zipkin.sender.type=web
#spring.sleuth.sampler.probability=1

